version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-1}
      - LS_LOG=info 
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

#version: "3.8"

#services:
#  localstack:
#    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
#    image: localstack/localstack
#    ports:
#      - "127.0.0.1:4566:4566"            # LocalStack Gateway
#      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
#    environment:
#      - DEBUG=${DEBUG-1}
#      - LS_LOG=info 
#      - LAMBDA_REMOVE_CONTAINERS=0 
#      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=60
#      - PROVIDER_OVERRIDE_LAMBDA=legacy
#      - LAMBDA_EXECUTOR=docker 
#      - DOCKER_HOST=unix:///var/run/docker.sock
#      - SERVICES=lambda,logs
#    volumes:
#      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"